#!/skcomms/php/bin/php -q
<?php
	define('PODO_CONFIG_KIWIDIR', '/skcomms/frw/kiwi');

    require_once dirname(__FILE__).'/Installer.php';

	if (count($argv) < 2 || in_array($argv[1], array('dev', 'live')) === false) {
		echo "Usage: init-prj [ dev | live ]\n";
		exit;
	}

    $installer = new Installer;
	$installer->setLive($argv[1] === 'live');
    $installer->install(TRUE);

    $strID = trim(`id -un`);

	if ($strID !== 'root') {
		if (file_exists('/home/'.$strID.'/public_html') === false) {
			mkdir('/home/'.$strID.'/public_html');
			chmod('/home/'.$strID, 0755);
		}

		if (file_exists(dirname(__FILE__).'/../docroot/~'.$strID) === FALSE) {
			symlink('/home/'.$strID.'/public_html', dirname(__FILE__).'/../docroot/~'.$strID);
		}

		if (is_link('/home/'.$strID.'/public_html/'.Installer::PJT_NAME)) {
			unlink('/home/'.$strID.'/public_html/'.Installer::PJT_NAME);
		}
		symlink(dirname(dirname(__FILE__)).'/docroot', '/home/'.$strID.'/public_html/'.Installer::PJT_NAME);
	}
?>
