<?php
// Call ArrayBuilderTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "ArrayBuilderTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once dirname(__FILE__).'/../../class/Podo/Dispatcher/ArrayFile.php';

/**
 * Test class for ArrayBuilder.
 * Generated by PHPUnit_Util_Skeleton on 2007-04-03 at 18:37:21.
 */
class ArrayBuilderTest extends PHPUnit_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("ArrayBuilderTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

	private $builder;
	private $filename;
    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    	$this->builder = new Podo_Dispatcher_ArrayFile;
    	$arr_array["1_1"]["2_1"] = "2_1";
    	$arr_array["1_1"]["2_2"] = "2_2";
    	$arr_array["1_2"] = "1_2";
    	$arr_array["1_3"] = "1_3";
    	$this->filename = dirname(__FILE__)."/arr_test.php";
		$this->builder->setArray($arr_array);
		$this->builder->setTarget($this->filename);
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    	if(file_exists($this->filename)){
    		unlink ($this->filename);
    	}
    }

    /**
     * @todo Implement testMakeArray2File().
     */
    public function testMakeArray2File() {
    	$result_rep  = "<?php\n";
    	$result_rep .= "\t\$test_array = array();\n";
    	$result_rep .= "\t\$test_array['1_1']['2_1'] = '2_1';\n";
    	$result_rep .= "\t\$test_array['1_1']['2_2'] = '2_2';\n";
    	$result_rep .= "\t\$test_array['1_2'] = '1_2';\n";
    	$result_rep .= "\t\$test_array['1_3'] = '1_3';\n";
    	$result_rep .= "?>\n";

    	$ret = $this->builder->makeArray2File("test_array");
    	$this->assertNotEquals($ret, FALSE);
    	
    	$result = file_get_contents($this->filename);
    	$this->assertEquals($result_rep, $result);
    }
}

// Call ArrayBuilderTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "ArrayBuilderTest::main") {
    ArrayBuilderTest::main();
}
?>
