<?php
// Call I18NParserTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "I18NParserTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once dirname(__FILE__).'/../../class/i18n/I18NParser.php';

/**
 * Test class for I18NParser.
 * Generated by PHPUnit_Util_Skeleton on 2007-03-28 at 16:19:10.
 */
class I18NParserTest extends PHPUnit_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("I18NParserTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

	private $parser;
    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    	$this->parser = new I18NParser;
    }

    /**
     * Tears down the fixture, for example, close a network connection.
     * This method is called after a test is executed.
     *
     * @access protected
     */
    protected function tearDown() {
    }

    /**
     * @todo Implement testGetDocument().
     */
    public function testGetDocument() {
    	$data="<aa><bb type='33'>111</bb><cc>222</cc><dd>111</dd><dd>222</dd><ee> </ee><ff></ff></aa>";
    	$result_rep = array();
    	$result_rep["AA"]["BB"] = "111";
    	$result_rep["AA"]["CC"] = "222";
    	$result_rep["AA"]["DD"] = "111222";
    	$result_rep["AA"]["EE"] = array();
    	$result_rep["AA"]["FF"] = array();
		$this->parser->parse_str($data);
		$result = $this->parser->getDocument();
		$this->assertEquals($result_rep, $result);
		
		//$this->assertEquals("222", $result["AA"][0]["BB"][1]["data"]);
    }

    /**
     * @todo Implement testParse_str().
     */
    public function testParse_str() {
       	$data = "<aa><bb>111</bb><cc/><dd>222</dd></aa>";
    	$this->assertTrue($this->parser->parse_str($data));
    }
}

// Call I18NParserTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "I18NParserTest::main") {
    I18NParserTest::main();
}
?>
