<?php
// Call I18NTest::main() if this source file is executed directly.
if (!defined("PHPUnit_MAIN_METHOD")) {
    define("PHPUnit_MAIN_METHOD", "I18NTest::main");
}

require_once "PHPUnit/Framework/TestCase.php";
require_once "PHPUnit/Framework/TestSuite.php";

require_once dirname(__FILE__).'/../../class/i18n/I18N.php';

/**
 * Test class for I18N.
 * Generated by PHPUnit_Util_Skeleton on 2007-04-03 at 17:01:37.
 */
class I18NTest extends PHPUnit_Framework_TestCase {
    /**
     * Runs the test methods of this class.
     *
     * @access public
     * @static
     */
    public static function main() {
        require_once "PHPUnit/TextUI/TestRunner.php";

        $suite  = new PHPUnit_Framework_TestSuite("I18NTest");
        $result = PHPUnit_TextUI_TestRunner::run($suite);
    }

    private $i18n;
    private $i18page;
    private $i18global;
    /**
     * Sets up the fixture, for example, open a network connection.
     * This method is called before a test is executed.
     *
     * @access protected
     */
    protected function setUp() {
    	$this->i18n = new I18N;
    	$i18page["hello"] = "¾È³çÇÏ¼¼¿ä!";
    	$i18page["love"] = "{\$boy}´Â {\$girl}À» »ç¶ûÇÕ´Ï´Ù.";
    	$this->i18page = $i18page;

    	$i18global["hello"] = "Hello!";
    	$i18global["bye"] = "Good bye, {\$user}!";
    	$this->i18global = $i18global;
    }

    /**
     * @todo Implement testSetPageMessage().
     */
    public function testSetPageMessage() {
        $this->i18n->setPageMessage($this->i18page);
        $result_rep = $this->i18page["hello"];
        $result = $this->i18n->getMessage("hello");
        $this->assertEquals($result_rep, $result);
    }

    /**
     * @todo Implement testSetGlabalMessage().
     */
    public function testSetGlabalMessage() {
        $this->i18n->setGlabalMessage($this->i18global);
        $result_rep = $this->i18global["hello"];
        $result = $this->i18n->getGlobal("hello");
        $this->assertEquals($result_rep, $result);
    }

    /**
     * @todo Implement testGetMessage().
     */
    public function testGetMessage() {
        $this->i18n->setPageMessage($this->i18page);
        $result_rep = "Åä³¢´Â »ç½¿À» »ç¶ûÇÕ´Ï´Ù.";
        $messagetag = array("boy"=>"Åä³¢","girl"=>"»ç½¿");
        $result = $this->i18n->getMessage("love",$messagetag);
        $this->assertEquals($result_rep, $result);

		$result_rep = "È£¶ûÀÌ´Â È£¶ûÀÌÀ» »ç¶ûÇÕ´Ï´Ù.";
        $messagetag = "È£¶ûÀÌ";
        $result = $this->i18n->getMessage("love",$messagetag);
        $this->assertEquals($result_rep, $result);
    }

    /**
     * @todo Implement testGetGlobal().
     */
    public function testGetGlobal() {
        $this->i18n->setGlabalMessage($this->i18global);
        $result_rep = "Good bye, Jane!";
        $messagetag = array("user"=>"Jane");
        $result = $this->i18n->getGlobal("bye",$messagetag);
        $this->assertEquals($result_rep, $result);

        $messagetag = "Jane";
        $result = $this->i18n->getGlobal("bye",$messagetag);
        $this->assertEquals($result_rep, $result);
    }
}

// Call I18NTest::main() if this source file is executed directly.
if (PHPUnit_MAIN_METHOD == "I18NTest::main") {
    I18NTest::main();
}
?>
